php::ensure: latest
php::manage_repos: true
php::fpm: true
php::dev: false
php::composer: false
php::pear: true
php::phpunit: false
php::fpm::config::log_level: notice
php::composer::auto_update: false

php::settings:
  Date/date.timezone: Europe/Berlin
php::cli::settings:
  PHP/memory_limit: 256M

php::extensions:
  gd: {}
  json: {}
  mcrypt: {}
  mysql: {}
  memcached:
    provider: pecl
    header_packages:
      - libmemcached-dev
  apc:
    package_prefix: php-
    settings:
      apc.stat: 1
      apc.stat_ctime: 1  